-- Migration: Adicionar suporte para credenciais Datecode por usuário
-- Data: 2025-10-18
-- Descrição: Permite que cada usuário tenha suas próprias credenciais Datecode

-- Verificar se a tabela credencias_diversas existe e tem o campo datecode
-- Se não existir, criar a tabela
CREATE TABLE IF NOT EXISTS public.credencias_diversas (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id bigint NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  google_calendar jsonb NULL DEFAULT '{"email": "", "refresh_token": ""}'::jsonb,
  asaas jsonb NULL DEFAULT '{"access_token": ""}'::jsonb,
  zapsign jsonb NULL DEFAULT '{"token": "", "modelos": ""}'::jsonb,
  datecode jsonb NULL DEFAULT '{"username": "", "password": ""}'::jsonb,
  CONSTRAINT credencias_diversas_pkey PRIMARY KEY (id),
  CONSTRAINT credencias_diversas_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Atualizar campo datecode se já existir mas com estrutura diferente
-- Garantir que o campo datecode tenha a estrutura correta
DO $$
BEGIN
  -- Verificar se a coluna datecode existe
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name = 'credencias_diversas'
    AND column_name = 'datecode'
  ) THEN
    -- Atualizar registros que tenham datecode em formato antigo
    UPDATE public.credencias_diversas
    SET datecode = jsonb_build_object(
      'username', COALESCE(datecode->>'DATECODE_USERNAME', ''),
      'password', COALESCE(datecode->>'DATECODE_PASSWORD', '')
    )
    WHERE datecode IS NOT NULL
    AND (datecode ? 'DATECODE_USERNAME' OR datecode ? 'DATECODE_PASSWORD');
  ELSE
    -- Se a coluna não existir, criar
    ALTER TABLE public.credencias_diversas
    ADD COLUMN datecode jsonb NULL DEFAULT '{"username": "", "password": ""}'::jsonb;
  END IF;
END $$;

-- Criar índice para melhorar performance de busca por user_id
CREATE INDEX IF NOT EXISTS idx_credencias_diversas_user_id
ON public.credencias_diversas(user_id);

-- Comentários na tabela e colunas
COMMENT ON TABLE public.credencias_diversas IS 'Armazena credenciais de serviços externos por usuário';
COMMENT ON COLUMN public.credencias_diversas.datecode IS 'Credenciais Datecode: {"username": "usuario", "password": "senha"}';
COMMENT ON COLUMN public.credencias_diversas.google_calendar IS 'Credenciais Google Calendar: {"email": "email@gmail.com", "refresh_token": "token"}';
COMMENT ON COLUMN public.credencias_diversas.asaas IS 'Credenciais Asaas: {"access_token": "token"}';
COMMENT ON COLUMN public.credencias_diversas.zapsign IS 'Credenciais ZapSign: {"token": "token", "modelos": ""}';
